### ISSUE TITLE
Pasi's Affiliation

### ISSUE THREAD

**Issue by seanturner** [emu-wg/draft-ietf-emu-rfc5448bis#1]
Pasi’s affiliation has changed.  But, I am unsure if you contacted him already and he wanted it left as Nokia.  If you haven’t contacted him already let me know and I can give you his info (off-list).

**Comment by jariarkko** [comment]
Yes. That needs to be fixed. I did now contact him, but if you have his affiliation data, send that to me... I would like to know though what he wants listed.

**Comment by jariarkko** [comment]
Got a word from Pasi. He wants to be listed as independent.
