### ISSUE TITLE
Flawed wording in SHA-256 assumtion?

### ISSUE THREAD

**Issue by seanturner** [emu-wg/draft-ietf-emu-rfc5448bis#10]
In ’09 when RFC 5488 was published, the following was true:

    We assume that
    SHA-256 is at least as secure as SHA-1.

But, sometime later in ’09 the wheels started to come off / came off of SHA-1 (but not SHA-256).  Later, the IETF published RFC 6194 that basically said SHA-1 is no-go unless it is used with HMAC.  Since EAP-AKA and EAP-AKA’ use HMAC should we tweak this sentence mention HMAC?  e.g.,

    We assume that HMAC
    SHA-256 is at least as secure as HMAC SHA-1.

We could also add a reference to RFC6194 assuming s3.3 still holds true?

Or should we rename the assumption the HMAC-SHA-256 assumption?

**Comment by jariarkko** [comment]
Yes. Thank you!! I have fixed all this in commit c5145b7.
