### ISSUE TITLE
s3.1: warn, wait, and then continue after getting a response?

### ISSUE THREAD

**Issue by seanturner** [emu-wg/draft-ietf-emu-rfc5448bis#4]
The draft contains the following:

    Upon detecting a discrepancy, the
    peer either warns the user and continues, or fails the authentication
    process. 

This really reads like it's going to provide a warning and continue regardless of what the user does.

**Comment by jariarkko** [comment]
Well... if you read the next sentences:
----
More specifically, the peer SHOULD have a configurable policy
that it can follow under these circumstances. If the policy indicates
that it can continue, the peer SHOULD log a warning message or display
it to the user.  If the peer chooses to proceed, it MUST use the
network name as received in the AT_KDF_INPUT attribute.  If the policy
indicates that the authentication should fail, the peer behaves as if
AUTN had been incorrect and authentication fails.
----
I think the requirement is pretty clear here. But I don't know if implementors will follow. Anything with user input is always an issue.

I don't plan to make changes wrt this point, do you think that's ok?

**Comment by seanturner** [comment]
> On Jan 17, 2019, at 08:00, Jari Arkko <notifications@github.com> wrote:
> 
> I don't plan to make changes wrt this point, do you think that's ok?

Yeah sorry I guess I flaked on the next bit :/

spt
